### ISSUE TITLE
Cloudflare link is down

### ISSUE THREAD

**Issue by joseph-allen** [Okazari/Rythm.js#118]
Using the Cloudflare link responds with a 404, not sure if this is just for me so if somebody else can confirm?

Needs to be either removed from docs or put back on cloudflare!

**Comment by Okazari** [comment]
Hey @joseph-allen, this links work fine for me : https://cdnjs.cloudflare.com/ajax/libs/rythm.js/2.2.5/rythm.min.js

Maybe it was unclear that you must replace 2.x.x with the version you want for your project. If so, you can make a PR to improve the doc in this direction 😉

**Comment by joseph-allen** [comment]
Should we replace the x's with the latest release, or keep as is? plus a note that it needs to be replaced by the user?

**Comment by Okazari** [comment]
I think it may be smarter to replace the x's with the latest release. Do you want to add you contribution to the project through this ? :smile:

**Comment by joseph-allen** [comment]
yeah I will do it :D

**Comment by joseph-allen** [comment]
༼ つ ◕_◕ ༽つ [https://github.com/Okazari/Rythm.js/pull/119](PR)

**Comment by Okazari** [comment]
Thanks ! And welcome as a contributor :smile:
