### ISSUE TITLE
any way to make the audio loop? 

### ISSUE THREAD

**Issue by xvap** [Okazari/Rythm.js#122]
i tried using 

`<audioid="music" class="music" src="resources/mw.mp3" autoplay loop onplaying="" style="display: none;"></audio>`
rythm.connectExternalAudioElement(music)

but that didnt work, could you maybe add like a loop feature? thanks in advance :)

**Comment by xvap** [comment]
solved it, my code was 
`
        audio id="music" class="music" src="resources/mw.mp3" autoplay loop onplaying="" style="display: none;"></audio>        
        var rythm = new Rythm()
        rythm.addRythm("blur1", "blur", 0, 250)
        rythm.addRythm("bass", "pulse", 0, 10)
        rythm.connectExternalAudioElement(document.getElementById("music"))
        rythm.setGain(0.5)
        rythm.start()
        document.getElementById("music").play()
        document.removeEventListener("mousedown",handleMouseDown)
`

**Comment by Okazari** [comment]
Glad you found a solution :) ! Feel free to ask if you have any more question.
