### ISSUE TITLE
Rythm constructor is not recognized

### ISSUE THREAD

**Issue by JustinDCole** [Okazari/Rythm.js#126]
I keep launching my file on the Live Server. I check console log, and I keep seeing the error Rythm is not a constructor, even though I've uploaded the library half a dozen times. What's wrong?

**Comment by Okazari** [comment]
Hello Justin, could you please continue your question on your initial thread ?

**Comment by JustinDCole** [comment]
> I keep launching my file on the Live Server. I check console log, and I keep seeing the error Rythm is not a constructor, even though I've uploaded the library half a dozen times. What's wrong?



> Hello Justin, could you please continue your questions on your initial thread ?
> #125
> 
> Also, it would help a lot to have a minimal reproduction of what you're currently doing. (Either by a link to your repo if it is public or by showing your code where you try to initialize Rythm.js)
> 
> I'll let you reach out to me with more details 😉

I just updated it.
