### ISSUE TITLE
Issue on song replay

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#24]
Copy/paste from #12

I found the reason : when the song replay this issue will happen

![2017-02-24_221753](https://cloud.githubusercontent.com/assets/7317546/23306605/38ae55ec-fadf-11e6-91f2-fc1714329dc0.png)

and i found this article http://stackoverflow.com/questions/35492397/remove-createmediaelementsource
any idea?

**Comment by Okazari** [comment]
@harrykc Could i have a look at the function fired on song's over ?

It looks like your player try to play a song that had already been connected to Rythm.js

**Comment by harrykc** [comment]
@Okazari I am just using APlayer and run following code in play event

```
ap.on('play', function() {
    rythm.connectExternalAudioElement(ap.audio);
    rythm.start();
})
```

https://github.com/DIYgod/APlayer/blob/master/src/APlayer.js
This is the APlayer source code, seems need to remove createMediaElementSource before next song?

**Comment by Okazari** [comment]
Hmmm i think i got the issue. But i need to a way to correct it.
If the track has already be played, `ap.audio` will be the same audio element. And you can't connect twice an audio element to a single audio context.

I got some solutions in my mind, but i need to investigate to get the most viable one. I'll be overwhelmed the whole next week. So i will probably not be able to work on Rythm before the 4th march.

Are you in a hurry ?

**Comment by harrykc** [comment]
Not hurry, just take your time, thank you :)

**Comment by Okazari** [comment]
Should be working in v2.0.4 (Finaly !)

Thanks for your patience @harrykc !
