### ISSUE TITLE
Add generic function handler as first argument to .addRythm

### ISSUE THREAD

**Issue by Lor-Saba** [Okazari/Rythm.js#25]
It would be nice to let who uses your lib a kind of "free will" to manipulate the dom as he/she feels like:

```js
rythm.addRythm(elementClass, danceType, startValue, nbValue);
rythm.addRythm(functionHandler, danceType, startValue, nbValue);

rythm.addRythm(function(event) {

    // event contains the current config and 
    // a .value which change from 0 to 1 based to the current rythm.
    myElement.style.opacity = event.value;

}, danceType, startValue, nbValue);
```

**Comment by Okazari** [comment]
@Lor-Saba That's a great idea ! I'm pretty much feeling that this would be for overidding the `danceType`

Like this you could use the built in danceTypes 

```js
// rythm.addRythm(elementClass, danceType, startValue, nbValue)
rythm.addRythm("myClass", "pulse", 50, 200);
```

and you could use you own danceType function

```js

// rythm.addRythm(elementClass, danceType, startValue, nbValue)
rythm.addRythm("myClass", (event) => {
   // Custom code using event.value
}, 50, 200);
```

The only negative point i find here is that people will probably do some awesome effects, and could not share them in the library :'(

I was refactoring to make PR really easy to do for effects (see #22) , woudn't it address this point ?

**Comment by Lor-Saba** [comment]
> @Lor-Saba That's a great idea ! I'm pretty much feeling that this would be for overidding the danceType

You're right, this makes more sense than my example.  
Also, an `event.target` which points to the current selected element would be useful (check the import below)


> The only negative point i find here is that people will probably do some awesome effects, and could not share them in the library :'(

You could try to add an "import" method, example:

```javascript
var danceTypes = {
    "blink": function(event){
        event.target.style.opacity = event.value > .5 ? 1 : 0;
    },
    "blink-smooth": function(event){
        event.target.style.opacity = event.value;
    },
    "bounce-right": function(event){
        event.target.style.transform = "translateX(" +(event.value * 50)+ "px)";
    }
};

rythm.importDanceTypes(danceTypes);
```
and then..
```javascript
rythm.addRythm("myClass", "blink-smooth", 50, 200);
```

p.s. 
thank you for considering my suggestion ^^
