### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by TBesta** [Okazari/Rythm.js#26]
**I've got this SyntaxError and why?**

SyntaxError: export declarations may only appear at top level of a module  rythm.js:1

**Comment by Okazari** [comment]
Hey @TBesta, how did you install Rythm ? Could you show me your import or script tag ?

**Comment by TBesta** [comment]
I just added it from ZIP but now used CDN and it's working. 

I think problem is in rythm.js which is in ZIP file.

**Comment by Okazari** [comment]
You currently cant use Rythm directly from github since this is the pre-build code. To use the production library file, use npm or CDNJS  ;)

**Comment by Okazari** [comment]
If you have any more question feel free to ask ! Hope youre enjoying Rythm :)
