### ISSUE TITLE
 audioelement is not defined

### ISSUE THREAD

**Issue by surmon-china** [Okazari/Rythm.js#27]
Hello, thank you for this powerful project!

I used the process found that when I use the `connectExternalAudioElement` method, it will prompt `audioelement is not defined`, seemingly because the compressed package variable name is not caused.

![image](https://cloud.githubusercontent.com/assets/14019524/24332216/572e1c5c-1275-11e7-90a8-4ad2f3c96961.png)

**Comment by Okazari** [comment]
Hey, thanks for your feedback.

This look like a stupid mistake from me (I should add some UnitTest to prevent this) i just wrote ```audioelement``` instead of ```audioElement```

I will hotfix this right now.

**Comment by Okazari** [comment]
I fixed this in v2.0.2, just update your dependency and it should work :) !

**Comment by surmon-china** [comment]
Oh, I missed a little ...

the `_this.audioElement` should be `_this.audio`

https://github.com/Okazari/Rythm.js/blob/master/rythm.js#L102

https://github.com/Okazari/Rythm.js/blob/master/rythm.js#L104

**Comment by Okazari** [comment]
You're right ! Wait a sec ;)

**Comment by Okazari** [comment]
v2.0.3 should be the one !
