### ISSUE TITLE
CORS error on remote mp3

### ISSUE THREAD

**Issue by mpint** [Okazari/Rythm.js#28]
Hello, I'm getting the following error when fetching audio sources from remote servers with the following code:

```
rythm.setMusic('https://archive.org/download/testmp3testfile/mpthreetest.mp3');

MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://archive.org/download/testmp3testfile/mpthreetest.mp3
```

Any thoughts on how to resolve this?

**Comment by gavinr** [comment]
If your audio file has the correct CORS headers (solution 3 above), you may still need to do:

```
rythm.player.audio.crossOrigin = "anonymous";
```

after you call the `setMusic()` function. ([more info](https://stackoverflow.com/a/32514394/2039))
