### ISSUE TITLE
Try to use github api to thanks contributors on demo page.

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#32]
They deserve it !

Probably will shout one person at a time, randomly selected from contributors.

**Comment by kounelios13** [comment]
what's that api?

**Comment by Okazari** [comment]
I would like to to something similar to https://botpress.io/ dashboard using regular github api https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts.
![image](https://user-images.githubusercontent.com/5747538/30248785-f16a7d28-962e-11e7-9fff-18f7e646da52.png)
