### ISSUE TITLE
Improve demo page UX

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#33]
Some people don't find easily how the demo page work.

Maybe adding an arrow that pulse to get attention from visitors ?

**Comment by ScreamingHawk** [comment]
I tried to click the boxes thinking they were radio buttons. 

I totally would have missed the `Start Demo` button if I didn't read other complaints on the HN article. 
People are there for the demo. Think it should be enabled by default.

**Comment by sunilkumarc** [comment]
@Okazari: Can i take this up and work on it?

**Comment by Okazari** [comment]
Hey !
Thanks for thé feedback @ScreamingHawk. That's the main issue of my demo page. I had this feedback several time. Anyway i don't want it tonne enable by default, i had way more complain about it than now.

Sure @sunilkumarc ! I really feel that a good solution here could be an attention seeker.

**Comment by Okazari** [comment]
The previously placed player will now show back when you scroll ;) !

**Comment by Okazari** [comment]
I also changed previous demo element with a note ascii char, to prevent confusion :)
