### ISSUE TITLE
get error when trying to run it

### ISSUE THREAD

**Issue by nikitavoloboev** [Okazari/Rythm.js#35]
I get this error when trying to run it : 

```Bash
yarn start v0.27.5
warning package.json: License should be a valid SPDX license expression
```

**Comment by nesvand** [comment]
What error are you getting in particular? Are you just pointing out that the license field should be updated?

**Comment by nikitavoloboev** [comment]
Yeah I suppose. But running `npm start` errors out with this error.

**Comment by nesvand** [comment]
So to be clear, you're saying `npm start` is crashing?

Can you give full logs from entering the command to returning to the command prompt?

**Comment by Okazari** [comment]
I found a little mistake in the new start script.
@nikitavoloboev It should work now ;) !

**Comment by Okazari** [comment]
Fixed with https://github.com/Okazari/Rythm.js/commit/d8799eb9bc8801c6660719c272ae9e5960bb2b85
