### ISSUE TITLE
Add an option to choose if on stop, elements should reset to their original position or not

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#38]
Currently, if you stop, it will stop the music and the element will not reset to their position.
I feel that the user should be able to choose the behavior.
I consider adding this into the library itself

This would required some changes like :
 - A way to provide the option or a "stopAndReset" function
 - Each dance would need a reset function that could be called to reset elements.

**Comment by kukiron** [comment]
Hi, do you mean the page to reload, with a Reset button maybe?

**Comment by Okazari** [comment]
I was thinking about stop button, or if the music stop also. It should be an option than whenever the library stop its job, elements css get resets.

**Comment by kukiron** [comment]
Opened a [PR](https://github.com/Okazari/Rythm.js/pull/48) for this.

Please check out.
