### ISSUE TITLE
Add a dance type playing with border-radius property

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#40]

**Comment by ajaymathur** [comment]
Hi, can you please elaborate this feature. :)

**Comment by Okazari** [comment]
I was thinking about just setting border-radius to let say 0px to 25px depending on the pulse ratio.
Here is the dance function signature https://github.com/Okazari/Rythm.js#custom-dance-type.
I think accepted options should be standards (min, max) and 'reverse' (default would be 25px => 0, reverse would be 0 => 25px)

Do you want to try ?

**Comment by ajaymathur** [comment]
Sure, I will give it a try.

**Comment by johnzmon** [comment]
I love it

**Comment by Okazari** [comment]
Done :)
