### ISSUE TITLE
Not working on Safari / Chrome (MacOS)

### ISSUE THREAD

**Issue by hiro28** [Okazari/Rythm.js#7]
Here is the console's log

> ReferenceError: Can't find variable: AudioContext

![screen shot 2017-02-17 at 11 08 56 am](https://cloud.githubusercontent.com/assets/4512141/23052139/87cd319a-f501-11e6-9d1b-90b09647314e.png)

**Comment by egoist** [comment]
You can add `if (typeof AudioContext !== 'undefined') {}` in your code, but it would better be fixed in the library itself, many browsers do not support this.

**Comment by Okazari** [comment]
I probably need to add a polyfill for safari. I will look how i can do this in a clean way.

**Comment by Okazari** [comment]
Just found this : `In Safari, the audio context has a prefix of webkit for backward-compatibility reasons. Since the Web Audio API is a work in progress, specification details may change.`

I'll go for this fix.

**Comment by Okazari** [comment]
I just updated the code and the demo, @hiro28 could you try it again on Safari ? If this works, i'll release a v1.2.4 with this patch.

**Comment by Okazari** [comment]
Someone reported that it didn't work in chrome on Mac too 😱

**Comment by Nouvan** [comment]
I'm currently debugging your code, since I want this proejct working on mobile phone.
I finaly get the music on mobile safari with this correction :

Line 167 :
this.browserAudioCtx = (typeof AudioContext == "undefined" || AudioContext == null)? window.webkitAudioContext: window.AudioContext;

However, the animations don't work properly. After some research, the main cause is on the analyser itself, but I didn't know the exact cause for the moment.

**Comment by Okazari** [comment]
Hey @Nouvan Thanks for the feedback !

The current code i already using this correction https://github.com/Okazari/Rythm.js/blob/master/src/Player.js#L5

It looks like safari will need a polyfill for this functionnality, i'll look in this way.

**Comment by Nouvan** [comment]
Hi @Okazari !

Did you try https://github.com/mohayonao/web-audio-engine ? Maybe it would be enough to make your project good on IOS devices ;) !

I will try soon and send you the results of my test.

**Comment by Okazari** [comment]
Thanks @Nouvan i appreciate.

I actually cannot work on Rythm.js because i got a lot of works and projects to finalize !

Anyway, thanks for the suggestion, i'll take a look. Still need to test if polyfills would be enougth tho.

**Comment by Okazari** [comment]
throwaway12933428233 on reddit :
Trouble is on this line:
`this.browserAudioCtx = AudioContext || webkitAudioContext`
If AudioContext is not defined, it throws an error. It doesn't fall back to webkitAudioContext. The script stops.
Easiest fix:
`this.browserAudioCtx = window.AudioContext || window.webkitAudioContext`
