### ISSUE TITLE
how to set volume for songs?

### ISSUE THREAD

**Issue by silent** [Okazari/Rythm.js#87]
i use the following script to set volume, but it obviously won't work w/ this:
```
<script>

	var audio = document.currentScript.parentElement;

	audio.volume = 0.3;

	</script>
```
Any way to do this?

**Comment by Okazari** [comment]
Hey @silent 

If you're using rythm as the player controller, your can use the `.gain()` function

```js
/* Adjust music's gain.
 * @value : Number
 */
rythm.setGain(value);
```

Should i improve the documentation to precise that gain is the technical word for volume ?

Tell me if you need anything else.

**Comment by silent** [comment]
Sorry aha, I didn't even realise, thank you ever so much.
