### ISSUE TITLE
any way to catch the audio is finished play?

### ISSUE THREAD

**Issue by jackbbhua** [Okazari/Rythm.js#88]
any way to catch the audio is finished play?
so we can move out rythm class,add new rythm class or change another css when new audio been loaded to rythem JS.
thank you very much.

**Comment by Okazari** [comment]
Hey Jackbbhua.

If you manage to get the audio element, you have the `ended` event.
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

Currently, if you want to get the audio element along with rythm.js you need to create and manage the audio element by yourself and use
```
/* Used to collaborate with other players library
 * You can connect Rythm to an audioElement, and then control the audio with your other player
 */
rythm.connectExternalAudioElement(audioElement)
```

I could also expose the `audio` element as `rythm.audio` (or you could do this as a PR ? ;) )

WDYT ?

**Comment by jackbbhua** [comment]
i will try it,let you know it will works or not.thank you Okazari.

**Comment by jackbbhua** [comment]
Hi, Okazari
I use ended event to catch the audio is end.it works.thank you in advance.

**Comment by Okazari** [comment]
Glad it worked :) !
